Merge tex-dependencies.txt
I learned that not all dependent files are downloaded by one file. So I have to list more dependencies by compiling many files by SwiftLaTeX

diff --git a/scripts/extract-accessed-url-from-har b/scripts/extract-accessed-url-from-har
--- a/scripts/extract-accessed-url-from-har
+++ b/scripts/extract-accessed-url-from-har
@@ -1,8 +1,29 @@
 #!/bin/bash
 
 set -eu
+set -o pipefail
+
+cmd="$1"
+har_file="$(readlink -f "$2")"
+
+extract_urls () {
+  jq -r .log.entries[].request.url < "$har_file" | tr -d '\r'
+}
 
 cd "$(dirname "$0")"/..
-har_file="$(readlink -f "$1")"
 
-jq -r .log.entries[].request.url < "$har_file" > tex-dependencies.txt
+case "$cmd" in
+  replace)
+    extract_urls | sort -u > tex-dependencies.txt
+    ;;
+  merge)
+    extract_urls > .tmp-added-tex-dependencies.txt
+    sort --unique tex-dependencies.txt .tmp-added-tex-dependencies.txt > .tmp-new-tex-dependencies.txt
+    mv .tmp-new-tex-dependencies.txt tex-dependencies.txt
+    rm .tmp-added-tex-dependencies.txt
+    ;;
+  *)
+    echo "Invalid command: '$cmd'"
+    exit 1
+    ;;
+esac
